In [1]:
import pandas as pd

election_result = pd.read_csv('./round07_election_result2.csv')
df = pd.DataFrame(election_result, columns=['광역시도', '시군', 'pop', 'minju', 'hanguk', 'gita'])
df

        광역시도    시군       pop    minju   hanguk      gita
0      서울특별시   종로구   81195.0  41148.0  18777.0   21270.0
1      서울특별시    중구   66474.0  34243.0  15618.0   16613.0
2      서울특별시   용산구  116054.0  53964.0  31073.0   31017.0
3      서울특별시   성동구  157863.0  84106.0  34878.0   38879.0
4      서울특별시   광진구  180373.0  99366.0  38606.0   42401.0
..       ...   ...       ...      ...      ...       ...
245     경상남도   산청군   24648.0   9779.0  12932.0    1937.0
246     경상남도   거창군   39547.0  13919.0  23022.0    2606.0
247     경상남도   합천군   32499.0  10330.0  19403.0    2766.0
248  제주특별자치도   제주시  250176.0  97935.0   8785.0  143456.0
249  제주특별자치도  서귀포시  100767.0  39966.0   2456.0   58345.0

[250 rows x 6 columns]